# Generated by Django 3.1 on 2020-08-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsSimpleMulti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
