# Generated by Django 3.1 on 2020-08-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsSimpleMulti', '0002_auto_20200831_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
