# Generated by Django 3.1 on 2020-08-21 12:49

import adminApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('format_date', models.CharField(max_length=20)),
                ('dataset', models.FileField(upload_to=adminApi.models.charger_dataset)),
            ],
        ),
    ]
