# Generated by Django 3.1 on 2020-08-22 08:40

import adminApi.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.FileField(upload_to=adminApi.models.charger_model)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApi.dataset')),
            ],
        ),
    ]
