# Generated by Django 3.1 on 2020-08-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0002_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='titre',
            field=models.CharField(default='allemand simple', max_length=100),
            preserve_default=False,
        ),
    ]
