# Generated by Django 3.1 on 2020-08-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0003_model_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='type_mod',
            field=models.CharField(default='simple', max_length=20),
        ),
    ]
