# Generated by Django 3.1 on 2020-09-04 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0005_auto_20200902_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_size', models.IntegerField()),
                ('optimizer', models.CharField(max_length=10)),
                ('learning_rate', models.FloatField()),
                ('epochs', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApi.model')),
            ],
        ),
    ]
